version: '3'
services:
  reverseshelllistener:
    build:
      context: .
      args:
        - NODE_ENV=local
      dockerfile: RS_Dockerfile
    ports:
      - "443:443"
    hostname: reverseShellListener
  proxy:
    build:
      context: .
      args:
        - NODE_ENV=local
      dockerfile: Proxy_Dockerfile
    ports:
      - "8080:8080"
    links:
      - reverseShellListener
    depends_on:
      - reverseShellListener

